### ISSUE TITLE
动图怎么做的？ 

### ISSUE THREAD

**Issue by hooper-hc** [MisterBooo/LeetCodeAnimation#1]
感觉蛮有意思的，应该挺耗时的吧

**Comment by MisterBooo** [comment]
使用PPT一帧一帧做的，是挺费时的：）

**Comment by fu1744** [comment]
ppt？厉害了， 老哥能不能来个教学。。

**Comment by MisterBooo** [comment]
后面会录个视频和大家交流一下PPT制作的经验：）

**Comment by fu1744** [comment]
好的，持续关注，谢谢

**Comment by Pomelo1213** [comment]
厉害了，没想到是ppt做的

**Comment by OctopusLian** [comment]
我最近也在刷LeetCode，不过你这个动态展示的形式还是很新颖的，而且还是用ppt做。
已fork，我后面也尝试做几个试试。^_^

**Comment by hooper-hc** [comment]
LEE 上1000 多题目， 做完老哥你就成仙了

**Comment by MisterBooo** [comment]
> 我最近也在刷LeetCode，不过你这个动态展示的形式还是很新颖的，而且还是用ppt做。
> 已fork，我后面也尝试做几个试试。^_^

欢迎欢迎，做完之后你可以pull request，或者加我微信我添加上去也行：）

**Comment by MisterBooo** [comment]
> LEE 上1000 多题目， 做完老哥你就成仙了

修仙之路很漫长：）

**Comment by xiaoxiaoyao** [comment]
可以用 PPT 录制动画，印象中有简单的制作动画方法

**Comment by yo1995** [comment]
Mark一下，有空帮忙添加几个动画 😄
