### ISSUE TITLE
问一下，你这个图是用什么软件画的

### ISSUE THREAD

**Issue by xiaofeng-bm** [MisterBooo/LeetCodeAnimation#105]

**Comment by zhubeilife** [comment]
https://github.com/MisterBooo/LeetCodeAnimation/issues/1
@xiaofeng-bm 善用搜索

**Comment by xiaofeng-bm** [comment]
哦哦，感谢 @zhubeilife

**Comment by FlowerBirds** [comment]
既然计划要用动画的方式来演示算法原理，就得找个合适的制作工具，这样才能事半功倍。一个做还不如找点志同道合的人，一起去完善。

**Comment by caohuanjun** [comment]
他回答你了吗？ @xiaofeng-bm

**Comment by xiaofeng-bm** [comment]
> 他回答你了吗？ @xiaofeng-bm

他回答了个毛，我一开始以为这些图都是百度搜出来的

**Comment by lnrCoder** [comment]
https://mp.weixin.qq.com/s/wy7graRRhfwbBzSPZHVl8Q

**Comment by ai977313677** [comment]
> 
> 
> > 他回答你了吗？ @xiaofeng-bm
> 
> 他回答了个毛，我一开始以为这些图都是百度搜出来的

人家回答的很清楚了，提问前为什么不搜一下issue呢？

**Comment by xiaofeng-bm** [comment]
> > > 他回答你了吗？ @xiaofeng-bm
> > 
> > 
> > 他回答了个毛，我一开始以为这些图都是百度搜出来的
> 
> 人家回答的很清楚了，提问前为什么不搜一下issue呢？#1点进去不就看到了？

不好意思，是我蠢了
