### ISSUE TITLE
there has a new repo which more problems be done

### ISSUE THREAD

**Issue by YUbuntu0109** [MisterBooo/LeetCodeAnimation#120]
thanks for your repo and looking forward to your suggestion bro : *www.algorithm.show*

**Comment by FlowerBirds** [comment]
看了一下你的网站，其中的《两数之和》算法题，解法就用了暴力计算，没有其他更巧妙的解法，只能让人看起来觉得就是一介武夫罢了。

**Comment by YUbuntu0109** [comment]
> 看了一下你的网站，其中的《两数之和》算法题，解法就用了暴力计算，没有其他更巧妙的解法，只能让人看起来觉得就是一介武夫罢了。

Thanks for your suggestions bro I will add new solution for it in the feature and so busy recently... Thanks again..
