### ISSUE TITLE
026-删除排序数组中的重复项

### ISSUE THREAD

**Issue by xyyanxin** [MisterBooo/LeetCodeAnimation#13]
解析思路 
 ` 如果不同，则两个指针都向前走一步 `
漏了一句，应该改为
 ` 如果不同，则两个指针都向前走一步  ，并且把快指针的值赋给（慢指针+1 )的位置`
不然容易误导

**Comment by MisterBooo** [comment]
感谢提醒，不过微信文章不好修改文字，我后续整理的时候再重新修改一下，笔芯
