### ISSUE TITLE
Any plan to develop an app?

### ISSUE THREAD

**Issue by Artwalk** [MisterBooo/LeetCodeAnimation#15]
Hi, Thanks for the animations, it is really a brilliant idea.

I checked your other repos, it seems you working on iOS platform a lot.
I think maybe there is someone like me who want to read it on cell phone when commuting.
So is there any plan to develop an app?  
If it is, maybe I can do something for help too :)

**Comment by MisterBooo** [comment]
Thanks for your attention and support, but I have no plan to design an APP at present：）
