### ISSUE TITLE
877号问题，数学问题补充。

### ISSUE THREAD

**Issue by wanglz111** [MisterBooo/LeetCodeAnimation#23]
最后数学分析部分，必须强调是偶数堆才能用这个思路。
[5,10000,3,4,5]
5(喜)->4(灰)->[5,10000,3]
我觉得这点应该作为分析的起点

只是最后一段，分析里没有提到，一开始理解有点困难，希望给后来的读者加上吧

**Comment by MisterBooo** [comment]
可以，加上去了
