### ISSUE TITLE
146可以多讲讲..

### ISSUE THREAD

**Issue by pengliheng** [MisterBooo/LeetCodeAnimation#27]
因为146的gif图解图片我加载不出来,也许是图片太大了.

**Comment by MisterBooo** [comment]
[LRU视频讲解](https://mp.weixin.qq.com/s?__biz=MzUyNjQxNjYyMg==&mid=2247484322&idx=1&sn=7a12bcef22dda2c97cffe8ad4d55ea9d&chksm=fa0e6c23cd79e53514cc85fb0a2bae55ab5965049eabf633ca537c0ecba1309db80119661b05&token=1340374584&lang=zh_CN#rd)
[看动画轻松理解「链表」实现「LRU缓存淘汰算法」](https://mp.weixin.qq.com/s?__biz=MzUyNjQxNjYyMg==&mid=2247484592&idx=2&sn=db47dd536f0e3c5705cd48f52e838c3a&chksm=fa0e6b31cd79e227951805f939d18495223fb1866cc50bf50ea1731a92ea23b6983d91a42564&token=1340374584&lang=zh_CN#rd)
你可以通过上面两个链接来学习一下 LRU 算法

**Comment by Yiyuery** [comment]
在 2019年6月10日，11:44，网管 <notifications@github.com<mailto:notifications@github.com>> 写道：
