### ISSUE TITLE
感谢博主分享的LeetCode图解

### ISSUE THREAD

**Issue by XINCGer** [MisterBooo/LeetCodeAnimation#7]
RT,感谢博主分享的LeetCode图解，一目了然，学到了很多知识，以前觉得一些深奥的算法现在也是非常容易理解，另外觉得PPT制作动画是不是有点不太方便，可以考虑使用AE或者Flash之类的制作下？或者可以专门开发一个小软件，如果需要帮忙的话 我会很乐意的，蛤蛤

**Comment by MisterBooo** [comment]
谢谢你的肯定，同时也很感谢你的建议，目前没接触过AE，我元旦期间研究一下看看效果怎么样：）

**Comment by YLJF** [comment]
@XINCGer hi，你可以共享个动画制作的小文章，如果有时间的话，我想大家都很期待，^_^
